# Generated by Django 4.0 on 2021-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_alter_post_options_rename_content_post_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='PostApp/static/img'),
        ),
    ]
