# Generated by Django 4.0 on 2021-12-19 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
