# Generated by Django 3.2.9 on 2021-12-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='imag_blog'),
        ),
    ]
