# Generated by Django 3.2.9 on 2021-12-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0010_comentario_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
