# Generated by Django 3.2.9 on 2021-12-22 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostApp', '0011_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('Pobreza', 'Pobreza'), ('Hambre', 'Hambre'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Igualdad de Género', 'Igualdad de Género'), ('Agua', 'Agua'), ('Energía', 'Energía'), ('Economía', 'Economía'), ('Infraestructura', 'Infraestructura'), ('Desigualdad', 'Desigualdad'), ('Ciudades', 'Ciudades'), ('Consumo', 'Consumo'), ('Cambio Climatico', 'Cambio Climatico'), ('Océanos', 'Océanos'), ('Biodiversidad', 'Biodiversidad'), ('Paz - Justicia ', 'Paz - Justicia '), ('Aliazas', 'Aliazas')], max_length=40, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_comment_author', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostApp.post')),
            ],
        ),
    ]
