# Generated by Django 3.2.9 on 2021-12-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0013_comentario_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='parent',
        ),
    ]
