# Generated by Django 3.2.9 on 2021-12-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuarios',
            name='registroApp_nombre_5f3b99_idx',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
    ]
