# Generated by Django 3.2.9 on 2021-12-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0002_auto_20211217_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['nombre', 'email'], name='registroApp_nombre_2fc8c4_idx'),
        ),
    ]
